### ISSUE TITLE
Central district and Manawatu area data does not appear to be accurate

### ISSUE THREAD

**Issue by GreigR** [nacnudus/nzpullover#1] opened 2017-02-20 07:24 UTC
Hi,

I was a Police Medical officer through this period of time. One of my duties was to collect blood samples from drunk drivers who declined to accept the breath test result. I would perform 2-5 blood samples per week and only 1:5 failed breath tests would request blood. So roughly there was 10+ drink or drug drivers per week. Yet this data set records only 238 offences in total or <1/week. 

For camera-issued and officer-issued speed tickets n = 186 for both categories. N = 186 also for running red lights and not wearing seat belts (restraints). For four significant categories over such a long time period to have a low number of offences with no variance, seems unlikely given the quality of NZ driving.

This data feels wrong.

Kind regards

Greig

**Comment by nacnudus** [comment] 2017-02-20 08:33
Hi Greig, Thanks for looking into the data.  Do you refer to particular subsets of the data, e.g. district/year?  Also, are you using the spreadsheet, the csv files, or the R dataset?

**Comment by GreigR** [comment] 2017-02-20 19:58
Many thanks for getting back to me. I was using the R dataset and focusing on the Manawatu area within the Central police district, as this is my home turf.

**Comment by nacnudus** [comment] 2017-02-21 00:57
Apart from 87 drug offences, I'm not able to reproduce the figures you quote.

``` r
library(nzpullover)
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats

driving_offences %>%
  filter(area == "Manawatu",
         series %in% c("Officer-issued speed offences",
                       "Drug specific offences",
                       "Officer issued red light")) %>%
  group_by(series) %>%
  summarise(value = sum(value))
#> # A tibble: 3 × 2
#>                          series value
#>                           <chr> <dbl>
#> 1        Drug specific offences    87
#> 2      Officer issued red light  1662
#> 3 Officer-issued speed offences 74216

driving_offences %>%
  filter(area == "Manawatu",
         series == "Officer-issued speed offences")
#> # A tibble: 93 × 6
#>                category value                        series district
#>                   <chr> <dbl>                         <chr>    <chr>
#> 1  Officer-issued Speed  1319 Officer-issued speed offences  Central
#> 2  Officer-issued Speed   996 Officer-issued speed offences  Central
#> 3  Officer-issued Speed  1144 Officer-issued speed offences  Central
#> 4  Officer-issued Speed  1139 Officer-issued speed offences  Central
#> 5  Officer-issued Speed  1231 Officer-issued speed offences  Central
#> 6  Officer-issued Speed  1191 Officer-issued speed offences  Central
#> 7  Officer-issued Speed  1189 Officer-issued speed offences  Central
#> 8  Officer-issued Speed  1511 Officer-issued speed offences  Central
#> 9  Officer-issued Speed  1143 Officer-issued speed offences  Central
#> 10 Officer-issued Speed  1129 Officer-issued speed offences  Central
#> # ... with 83 more rows, and 2 more variables: area <chr>, month <date>
```

For the 87, drug offences, the caveats point out that there are also combined drug & alcohol offence codes, which can't be separated out.  If they could be, then the number of drug offences might match your experience.  But since the 87 is correctly derived from the spreadsheet, I can't investigate any further.  I did used to work for the team that releases the data, but I don't any more, and this is an unofficial package.  I will update the README to point this out.  I'm sure the NZ Police would respond to a query.

**Comment by GreigR** [comment] 2017-02-21 07:26
Hi,

Many thanks for that. attached is my notebook as to how I got the numbers I did.

Kind regards

Greigt
[Traffic_manawatu.pdf](https://github.com/nacnudus/nzpullover/files/789350/Traffic_manawatu.pdf)

**Comment by nacnudus** [comment] 2017-02-21 09:01
`fct_count` is counting the number of cells, not summing the values (offences) in the cells. To do that, try something like my code above.

**Comment by GreigR** [comment] 2017-02-22 00:24
Many thanks for all your help. Can you suggest anyone in particular to contact in NZ Police?

Cheers

Greig

**Comment by nacnudus** [comment] 2017-02-22 18:31
They seem to have an email address for data enquiries [data@police.govt.nz](data@police.govt.nz), but remember they only produce the source spreadsheet, not this R package.

I will close this issue.  If you find any discrepancies between the spreadsheet and the R datasets, feel free to open a new issue.

**Closed as completed by nacnudus** 2017-02-22 18:31 UTC
